# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: Cook4us\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.edit.profile:
          class: Cook4us\Form\Type\ProfileFormType
          tags:
              - { name: form.type, alias: app_user_edit_profile }